---
apiVersion: koreo.dev/v1beta1
kind: ResourceFunction
metadata:
  name: gcp-environment-iam-service-account
spec:
  locals:
    name: =inputs.metadata.name + "-workload-identity"
  apiConfig:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: =locals.name
    namespace: =inputs.metadata.namespace

  resource:
    spec:
      displayName: "GKE remote access via WI"
  postconditions:
    - assert: =resource.config_connect_ready()
      retry:
        message: Waiting for connector to be created
        delay: 10

  return:
    name: =locals.name
    member: =resource.status.member
