---
apiVersion: koreo.dev/v1beta1
kind: ResourceFunction
metadata:
  name: federated-iam-policy-member
spec:
  locals:
    name: =inputs.metadata.name + "-workload-identity"
  apiConfig:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMPolicyMember
    name: =locals.name
    namespace: =inputs.metadata.namespace

  resource:
    spec:
      member: =inputs.saMember
      role: roles/container.developer
      resourceRef:
        kind: Project
        external: ="projects/" + inputs.projectId
        
  postconditions:
    - assert: =resource.config_connect_ready()
      retry:
        message: Waiting for connector to be created
        delay: 10

  return:
    name: =locals.name
