apiVersion: koreo.dev/v1beta1
kind: Workflow
metadata:
  name: gcp-environment
spec:
  crdRef:
    apiGroup: example.koreo.dev
    version: v1beta1
    kind: GcpEnvironment
    
  steps:
    - label: metadata
      ref:
        name: gcp-environment-metadata
        kind: ValueFunction
      inputs:
        environmentResourceName: =parent.metadata.name
        environmentNamespace: =parent.metadata.namespace

    - label: network
      ref:
        kind: ResourceFunction
        name: gcp-environment-network
      inputs:
        metadata: =steps.metadata
      state:
        networkName: =value.name

    - label: subnet
      ref:
        kind: ResourceFunction
        name: gcp-environment-subnet
      inputs:
        metadata: =steps.metadata
        networkName: =steps.network.name
        range: 10.10.0.0/16
      state:
        subnetName: =value.name

    - label: firewall
      ref:
        kind: ResourceFunction
        name: gcp-environment-firewall
      inputs:
        metadata: =steps.metadata
        networkName: =steps.network.name
        subnet: =steps.subnet
