apiVersion: koreo.dev/v1beta1
kind: ResourceFunction
metadata:
  name: aws-environment-internet-gateway
spec:
  apiConfig:
    apiVersion: ec2.services.k8s.aws/v1alpha1
    kind: InternetGateway
    name: =inputs.metadata.name
    namespace: =inputs.metadata.namespace

  create:
    delay: 1

  resource:
    metadata: =inputs.metadata
    spec:
      vpcRef:
        from:
          name: =inputs.vpc.name
      tags: =inputs.resource_tags.tags

  postconditions:
    - assert: =has(resource.status.internetGatewayID)
      retry:
        message: Waiting for internet gateway to become healthy
        delay: 5

  return:
    name: =inputs.metadata.name
    gateway_id: =resource.status.internetGatewayID
---
apiVersion: koreo.dev/v1beta1
kind: FunctionTest
metadata:
  name: aws-environment-internet-gateway-test
spec:
  functionRef:
    kind: ResourceFunction
    name: aws-environment-internet-gateway
  inputs:
    vpc:
      name: test-vpc
    metadata:
      name: test
      namespace: test-namespace
    resource_tags:
      tags:
        - key: test
          value: value

  testCases:
   - expectResource:
       apiVersion: ec2.services.k8s.aws/v1alpha1
       kind: InternetGateway
       metadata:
         name: test
         namespace: test-namespace
       spec:
         tags:
         - key: test
           value: value
         vpcRef:
           from:
             name: test-vpc

---
apiVersion: koreo.dev/v1beta1
kind: FunctionTest
metadata:
  name: aws-environment-internet-gateway-test-validation
spec:
  functionRef:
    kind: ResourceFunction
    name: aws-environment-internet-gateway
  inputs:
    vpc:
      name: test-vpc
    metadata:
      name: test
      namespace: test-namespace
    resource_tags:
      tags:
      - key: test
        value: value

  currentResource:
    apiVersion: ec2.services.k8s.aws/v1alpha1
    kind: InternetGateway
    metadata:
      name: test
      namespace: test-namespace
    spec:
      tags:
      - key: test
        value: value
      vpcRef:
        from:
          name: test-vpc
    status:
      internetGatewayID: ig-2453445123

  testCases:
    - expectReturn:
        name: test
        gateway_id: ig-2453445123
