apiVersion: koreo.dev/v1beta1
kind: ValueFunction
metadata:
  name: gcp-environment-config
spec:
  return:
    environmentNamespace: =inputs.parent.metadata.namespace
    environmentResourceName: =inputs.parent.metadata.name
    projectId: =inputs.parent.spec.projectId
---
apiVersion: koreo.dev/v1beta1
kind: FunctionTest
metadata:
  name: gcp-environment-config-test
spec:
  functionRef:
    kind: ValueFunction
    name: gcp-environment-config

  inputs:
    parent:
      apiVersion: acme.example.com/v1beta1
      kind: GcpEnvironment
      metadata:
        name: test-gcp-environment
        namespace: test-namespace
      spec:
        projectId: test-project

  testCases:
  - expectReturn:
      environmentNamespace: test-namespace
      environmentResourceName: test-gcp-environment
      projectId: test-project
